### ISSUE TITLE
FEAT: we need to support end-to-end encryption otherwise we can't support Matrix chats

### ISSUE THREAD

**Issue by fplord** [igneous-labs/omnispace#42]
```matrix.js:113404 Uncaught (in promise) Error: This room is configured to use encryption, but your client does not support encryption.
    at MatrixClient.encryptEventIfNeeded (matrix.js:113404:19)
    at matrix.js:113310:44
```

**Comment by fplord** [comment]
https://spec.matrix.org/v1.6/client-server-api/#uploading-keys

Quite a pain to implement but this will allow us to do matrix user <--> matrix user conversations
